### ISSUE TITLE
Update soundEnum for 1.13+

### ISSUE THREAD

**Issue by dextonanderson** [Ruinscraft/Powder#6]
The `soundEnum` option in the default `powders.yml` is using old 1.12 enum values. A lot of them, especially relating to note sounds have broken. There should be some compatibility between 1.12 and 1.13+ here

**Comment by drewdorris** [comment]
NoteBlockAPI handles this https://github.com/koca2000/NoteBlockAPI/blob/master/src/main/java/com/xxmicloxx/NoteBlockAPI/model/Sound.java
https://github.com/Ruinscraft/Powder/blob/master/src/main/java/com/ruinscraft/powder/util/ConfigUtil.java#L253
